name: Check New Tags

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  check_tags:
    runs-on: self-hosted
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Get existing tags
        id: get-tags
        run: |
          # Fetching existing tags
          existing_tags="${{ vars.LTS_TAGS }}"

          # Fetching tags
          tags=$(git ls-remote --tags https://github.com/vyos/vyos-build "refs/tags/1.4*" | cut -d/ -f3 | tr '\n' ' ')

          # If the variable is empty, populate it and exit
          if [[ -z "$existing_tags" ]]; then
            echo "LTS_TAGS=$tags" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          # Check for new tags and update environment variable
          for tag in $tags; do
            if [[ ! "$existing_tags" =~ "$tag" ]]; then
              echo "NEW_LTS_TAG=$tag" >> "$GITHUB_OUTPUT"
              existing_tags="$existing_tags $tag"
            fi
          done

          # If the list of LTS tags has changed, update it
          if [[ "$existing_tags" != "${{ vars.LTS_TAGS }}" ]]; then
            echo "LTS_TAGS=$existing_tags" >> "$GITHUB_OUTPUT"
          fi

      - name: Update LTS Tags
        if: ${{ steps.get-tags.outputs.LTS_TAGS != '' }}
        uses: action-pack/set-variable@v1
        with:
          name: 'LTS_TAGS'
          value: ${{ steps.get-tags.outputs.LTS_TAGS }}
          token: ${{ steps.app-token.outputs.token }}

      - name: Update LTS Tag
        if: ${{ steps.get-tags.outputs.NEW_LTS_TAG != '' }}
        uses: action-pack/set-variable@v1
        with:
          name: 'LTS_TAG'
          value: ${{ steps.get-tags.outputs.NEW_LTS_TAG }}
          token: ${{ steps.app-token.outputs.token }}
    outputs:
      NEW_LTS_TAG: ${{ steps.get-tags.outputs.NEW_LTS_TAG }}
  build-new-lts:
    name: Build New LTS
    needs: check_tags
    if: ${{ needs.check_tags.outputs.NEW_LTS_TAG != '' }}
    secrets: inherit
    permissions:
      contents: write
    uses: ./.github/workflows/lts-1.4.x.yaml
    with:
      LTS_TAG: ${{ needs.check_tags.outputs.NEW_LTS_TAG }}